---
# cert-manager defaults

# cert_manager_version is defined in group_vars/all.yml
# cert_manager_email is defined in group_vars/all.yml
# domain is defined in group_vars/all.yml

# Which Let's Encrypt issuer to use: "production" or "staging"
# Staging has higher rate limits but produces untrusted certificates
cert_manager_issuer: staging
