apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Release.Name }}-synapse-secrets
  namespace: {{ .Values.namespace }}
spec:
  # The path to the item in your 1Password Vault
  # Format: vaults/<vault-id>/items/<item-id>
  itemPath: "vaults/{{ .Values.synapse.onepassword.vaultId }}/items/{{ .Values.synapse.onepassword.itemId }}"
type: Opaque
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Release.Name }}-synapse-smtp-secrets
  namespace: {{ .Values.namespace }}
spec:
  itemPath: "vaults/{{ .Values.synapse.onepassword.vaultId }}/items/{{ .Values.synapse.onepassword.smtpItemId }}"

