namespace: matrix
domain: twobitrobit.com
synapse:
  onepassword:
    vaultId: "Anchor Kubernetes"
    itemId: "SynapseServerSecrets"
    smtpItemId: "Anchor SMTP Resend.com API Credentials"
  replicaCount: 1
  image:
    repository: docker.io/matrixdotorg/synapse
    tag: latest
  service:
    type: ClusterIP
    port: 8008
wellKnown:
  replicaCount: 1
  image:
    repository: docker.io/nginxinc/nginx-unprivileged
    tag: latest
  service:
    type: ClusterIP
    port: 80
